/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Management;

import javax.swing.*;
import java.awt.*;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.List;

/**
 *
 * @author anicia
 */
public class ViewRoom extends JFrame {

    /**
     * Creates new form ViewRoom
     */
    public ViewRoom(int UserLogin, int hall) {
        this.UserLogin=UserLogin;
        this.hall=hall;
        initComponents();
        fillInComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new JPanel();
        jPanel2 = new JPanel();
        jPanel11 = new JPanel();
        jLabelLOGOUT = new JLabel();
        jLabel3 = new JLabel();
        jSeparator2 = new JSeparator();
        jSeparator3 = new JSeparator();
        jPanel3 = new JPanel();
        jPanel4 = new JPanel();
        jLabelVIEW = new JLabel();
        jPanel5 = new JPanel();
        jLabelORDERS = new JLabel();
        jPanel7 = new JPanel();
        jLabelMERGE = new JLabel();
        jPanel8 = new JPanel();
        jLabelSPLIT = new JLabel();
        jPanel9 = new JPanel();
        jLabelBOOK = new JLabel();
        jPanel12 = new JPanel();
        jLabelB = new JLabel();
        jLabelA = new JLabel();
        jLabel19 = new JLabel();
        jLabel4 = new JLabel();
        jLabelD = new JLabel();
        jLabelC = new JLabel();
        jLabelF = new JLabel();
        jLabelI = new JLabel();
        jLabelJ = new JLabel();
        jLabelH = new JLabel();
        jLabelG = new JLabel();
        jLabelE = new JLabel();
        jLabelL = new JLabel();
        jLabelM = new JLabel();
        jLabelN = new JLabel();
        jLabelO = new JLabel();
        jLabelP = new JLabel();
        jLabelS = new JLabel();
        jLabelT = new JLabel();
        jLabelU = new JLabel();
        jLabelR = new JLabel();
        jLabelQ = new JLabel();
        jLabelY = new JLabel();
        jLabelX = new JLabel();
        jLabelW = new JLabel();
        jLabelV = new JLabel();
        jLabelK = new JLabel();
        jLabel16 = new JLabel();
        jPanel6 = new JPanel();
        jPanel10 = new JPanel();
        jPanel13 = new JPanel();
        jPanel14 = new JPanel();
        jLabel11 = new JLabel();
        jSeparator1 = new JSeparator();

        labelList.add(jLabelA);
        labelList.add(jLabelB);
        labelList.add(jLabelC);
        labelList.add(jLabelD);
        labelList.add(jLabelE);
        labelList.add(jLabelF);
        labelList.add(jLabelG);
        labelList.add(jLabelH);
        labelList.add(jLabelI);
        labelList.add(jLabelJ);
        labelList.add(jLabelK);
        labelList.add(jLabelL);
        labelList.add(jLabelM);
        labelList.add(jLabelN);
        labelList.add(jLabelO);
        labelList.add(jLabelP);
        labelList.add(jLabelQ);
        labelList.add(jLabelR);
        labelList.add(jLabelS);
        labelList.add(jLabelT);
        labelList.add(jLabelU);
        labelList.add(jLabelV);
        labelList.add(jLabelW);
        labelList.add(jLabelX);
        labelList.add(jLabelY);

        for (JLabel label : labelList) {
            //label.setVisible(false);
            label.setFont(new Font("Tahoma", 0, 14)); // NOI18N
            label.setForeground(new Color(0,0,0));
            label.setIconTextGap(15);
        }


        jLabelA.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                String tableID = jLabelA.getText();
                TableClicked(evt,tableID);
            }
        });
        jLabelB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                String tableID = jLabelB.getText();
                TableClicked(evt,tableID);
            }
        });
        jLabelC.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                String tableID = jLabelC.getText();
                TableClicked(evt,tableID);
            }
        });
        jLabelD.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                String tableID = jLabelD.getText();
                TableClicked(evt,tableID);
            }
        });
        jLabelE.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                String tableID = jLabelE.getText();
                TableClicked(evt,tableID);
            }
        });
        jLabelF.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                String tableID = jLabelF.getText();
                TableClicked(evt,tableID);
            }
        });
        jLabelG.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                String tableID = jLabelG.getText();
                TableClicked(evt,tableID);
            }
        });
        jLabelH.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                String tableID = jLabelH.getText();
                TableClicked(evt,tableID);
            }
        });
        jLabelI.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                String tableID = jLabelI.getText();
                TableClicked(evt,tableID);
            }
        });
        jLabelJ.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                String tableID = jLabelJ.getText();
                TableClicked(evt,tableID);
            }
        });
        jLabelK.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                String tableID = jLabelK.getText();
                TableClicked(evt,tableID);
            }
        });
        jLabelL.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                String tableID = jLabelL.getText();
                TableClicked(evt,tableID);
            }
        });
        jLabelM.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                String tableID = jLabelM.getText();
                TableClicked(evt,tableID);
            }
        });
        jLabelN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                String tableID = jLabelN.getText();
                TableClicked(evt,tableID);
            }
        });
        jLabelO.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                String tableID = jLabelO.getText();
                TableClicked(evt,tableID);
            }
        });
        jLabelP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                String tableID = jLabelP.getText();
                TableClicked(evt,tableID);
            }
        });
        jLabelQ.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                String tableID = jLabelQ.getText();
                TableClicked(evt,tableID);
            }
        });
        jLabelR.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                String tableID = jLabelR.getText();
                TableClicked(evt,tableID);
            }
        });
        jLabelS.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                String tableID = jLabelS.getText();
                TableClicked(evt,tableID);
            }
        });
        jLabelT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                String tableID = jLabelT.getText();
                TableClicked(evt,tableID);
            }
        });
        jLabelU.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                String tableID = jLabelU.getText();
                TableClicked(evt,tableID);
            }
        });
        jLabelV.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                String tableID = jLabelV.getText();
                TableClicked(evt,tableID);
            }
        });
        jLabelW.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                String tableID = jLabelW.getText();
                TableClicked(evt,tableID);
            }
        });
        jLabelX.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                String tableID = jLabelX.getText();
                TableClicked(evt,tableID);
            }
        });
        jLabelY.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                String tableID = jLabelY.getText();
                TableClicked(evt,tableID);
            }
        });

        jLabelVIEW.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ViewClicked(evt);
            }
        });
        jLabelORDERS.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                OrdersClicked(evt);
            }
        });
        jLabelMERGE.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MergeClicked(evt);
            }
        });
        jLabelSPLIT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SplitClicked(evt);
            }
        });
        jLabelBOOK.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BookClicked(evt);
            }
        });
        jLabelLOGOUT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LogoutClicked(evt);
            }
        });

        setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new Color(51, 51, 51));
        jPanel1.setPreferredSize(new Dimension(2050, 680));

        jPanel2.setBackground(new Color(51, 51, 51));
        jPanel2.setPreferredSize(new Dimension(1140, 88));

        jPanel11.setBackground(new Color(51, 51, 51));

        jLabelLOGOUT.setBackground(new Color(51, 51, 51));
        jLabelLOGOUT.setForeground(new Color(255, 255, 255));
        jLabelLOGOUT.setIcon(new ImageIcon(getClass().getResource("/icons/logout.png"))); // NOI18N
        jLabelLOGOUT.setText("LOG OUT");
        jLabelLOGOUT.setHorizontalTextPosition(SwingConstants.RIGHT);
        jLabelLOGOUT.setIconTextGap(20);

        GroupLayout jPanel11Layout = new GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelLOGOUT, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabelLOGOUT, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel3.setBackground(new Color(204, 204, 204));
        jLabel3.setFont(new Font("Century Gothic", 0, 12)); // NOI18N
        jLabel3.setForeground(new Color(255, 255, 255));
        jLabel3.setIcon(new ImageIcon(getClass().getResource("/icons/arms.png"))); // NOI18N
        jLabel3.setText("A U T O M A T I C   R E S T A U R A N T   M A N A G E M E N T   S Y S T E M ");
        jLabel3.setIconTextGap(10);

        jSeparator2.setBackground(new Color(204, 204, 204));
        jSeparator2.setForeground(new Color(255, 255, 255));

        jSeparator3.setBackground(new Color(204, 204, 204));
        jSeparator3.setForeground(new Color(255, 255, 255));

        GroupLayout jPanel2Layout = new GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(jPanel2Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, GroupLayout.PREFERRED_SIZE, 458, GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator3, GroupLayout.PREFERRED_SIZE, 476, GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, 478, Short.MAX_VALUE)
                .addComponent(jPanel11, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSeparator2, GroupLayout.PREFERRED_SIZE, 481, GroupLayout.PREFERRED_SIZE)
                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jPanel11, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jSeparator2, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)
                        .addComponent(jLabel3)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator3, GroupLayout.PREFERRED_SIZE, 10, GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new Color(51, 51, 51));

        jPanel4.setBackground(new Color(51, 51, 51));

        jLabelVIEW.setForeground(new Color(255, 255, 255));
        jLabelVIEW.setIcon(new ImageIcon(getClass().getResource("/icons/floor.png"))); // NOI18N
        jLabelVIEW.setText("VIEW");
        jLabelVIEW.setHorizontalTextPosition(SwingConstants.RIGHT);
        jLabelVIEW.setIconTextGap(30);

        jPanel5.setBackground(new Color(51, 51, 51));

        jLabelORDERS.setForeground(new Color(255, 255, 255));
        jLabelORDERS.setIcon(new ImageIcon(getClass().getResource("/icons/orders.png"))); // NOI18N
        jLabelORDERS.setText("ORDERS");
        jLabelORDERS.setHorizontalTextPosition(SwingConstants.RIGHT);
        jLabelORDERS.setIconTextGap(25);

        GroupLayout jPanel5Layout = new GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(45, Short.MAX_VALUE)
                .addComponent(jLabelORDERS, GroupLayout.PREFERRED_SIZE, 129, GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelORDERS, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        GroupLayout jPanel4Layout = new GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelVIEW, GroupLayout.PREFERRED_SIZE, 129, GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addComponent(jPanel5, GroupLayout.Alignment.TRAILING, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelVIEW, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        );

        jPanel7.setBackground(new Color(51, 51, 51));

        jLabelMERGE.setForeground(new Color(255, 255, 255));
        jLabelMERGE.setIcon(new ImageIcon(getClass().getResource("/icons/merge.png"))); // NOI18N
        jLabelMERGE.setText("MERGE");
        jLabelMERGE.setHorizontalTextPosition(SwingConstants.RIGHT);
        jLabelMERGE.setIconTextGap(30);

        GroupLayout jPanel7Layout = new GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelMERGE, GroupLayout.PREFERRED_SIZE, 130, GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addComponent(jLabelMERGE, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel8.setBackground(new Color(51, 51, 51));

        jLabelSPLIT.setForeground(new Color(255, 255, 255));
        jLabelSPLIT.setIcon(new ImageIcon(getClass().getResource("/icons/split.png"))); // NOI18N
        jLabelSPLIT.setText("SPLIT");
        jLabelSPLIT.setHorizontalTextPosition(SwingConstants.RIGHT);
        jLabelSPLIT.setIconTextGap(30);

        jPanel9.setBackground(new Color(51, 51, 51));

        jLabelBOOK.setForeground(new Color(255, 255, 255));
        jLabelBOOK.setIcon(new ImageIcon(getClass().getResource("/icons/book.png"))); // NOI18N
        jLabelBOOK.setText("BOOK");
        jLabelBOOK.setHorizontalTextPosition(SwingConstants.RIGHT);
        jLabelBOOK.setIconTextGap(30);

        GroupLayout jPanel9Layout = new GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelBOOK, GroupLayout.PREFERRED_SIZE, 133, GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addComponent(jLabelBOOK, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        GroupLayout jPanel8Layout = new GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelSPLIT, GroupLayout.PREFERRED_SIZE, 133, GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addComponent(jPanel9, GroupLayout.Alignment.TRAILING, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addComponent(jLabelSPLIT, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel9, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );

        GroupLayout jPanel3Layout = new GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel7, GroupLayout.Alignment.TRAILING, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel8, GroupLayout.Alignment.TRAILING, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(119, 119, 119)
                .addComponent(jPanel4, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel7, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel8, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addContainerGap(201, Short.MAX_VALUE))
        );

        jPanel12.setBackground(new Color(255, 255, 255));
        jPanel12.setPreferredSize(new Dimension(929, 622));

        jLabel19.setFont(new Font("Tahoma", 0, 12)); // NOI18N
        jLabel19.setIcon(new ImageIcon(getClass().getResource("/icons/go_back.png"))); // NOI18N
        jLabel19.setText("GO BACK");
        jLabel19.setToolTipText("");
        jLabel19.setIconTextGap(1);

        jLabel4.setFont(new Font("Tahoma", 0, 9)); // NOI18N
        jLabel4.setIcon(new ImageIcon(getClass().getResource("/icons/status_table.png"))); // NOI18N
        jLabel4.setText("LEGEND");
        jLabel4.setHorizontalTextPosition(SwingConstants.CENTER);
        jLabel4.setIconTextGap(10);
        jLabel4.setInheritsPopupMenu(false);
        jLabel4.setVerifyInputWhenFocusTarget(false);
        jLabel4.setVerticalTextPosition(SwingConstants.TOP);

        jLabel16.setFont(new Font("Tahoma", 0, 12)); // NOI18N
        jLabel16.setText("Click on to choose a table");

        GroupLayout jPanel12Layout = new GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addComponent(jLabel19, GroupLayout.PREFERRED_SIZE, 103, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4, GroupLayout.PREFERRED_SIZE, 88, GroupLayout.PREFERRED_SIZE))
            .addGroup(GroupLayout.Alignment.TRAILING, jPanel12Layout.createSequentialGroup()
                .addGap(0, 120, Short.MAX_VALUE)
                .addGroup(jPanel12Layout.createParallelGroup(GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabelC, GroupLayout.PREFERRED_SIZE, 115, GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelD, GroupLayout.Alignment.TRAILING, GroupLayout.PREFERRED_SIZE, 115, GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelB, GroupLayout.Alignment.TRAILING, GroupLayout.PREFERRED_SIZE, 115, GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelA, GroupLayout.Alignment.TRAILING, GroupLayout.PREFERRED_SIZE, 115, GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelE, GroupLayout.Alignment.TRAILING, GroupLayout.PREFERRED_SIZE, 115, GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel12Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelH, GroupLayout.Alignment.TRAILING, GroupLayout.PREFERRED_SIZE, 115, GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelI, GroupLayout.Alignment.TRAILING, GroupLayout.PREFERRED_SIZE, 115, GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelG, GroupLayout.Alignment.TRAILING, GroupLayout.PREFERRED_SIZE, 115, GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelF, GroupLayout.Alignment.TRAILING, GroupLayout.PREFERRED_SIZE, 115, GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelJ, GroupLayout.Alignment.TRAILING, GroupLayout.PREFERRED_SIZE, 115, GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel12Layout.createParallelGroup(GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addGroup(jPanel12Layout.createParallelGroup(GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabelN, GroupLayout.PREFERRED_SIZE, 115, GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelO, GroupLayout.Alignment.TRAILING, GroupLayout.PREFERRED_SIZE, 115, GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelM, GroupLayout.Alignment.TRAILING, GroupLayout.PREFERRED_SIZE, 115, GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelL, GroupLayout.Alignment.TRAILING, GroupLayout.PREFERRED_SIZE, 115, GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(jPanel12Layout.createParallelGroup(GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabelT, GroupLayout.PREFERRED_SIZE, 115, GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelS, GroupLayout.PREFERRED_SIZE, 115, GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelQ, GroupLayout.PREFERRED_SIZE, 115, GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelR, GroupLayout.PREFERRED_SIZE, 115, GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addComponent(jLabelK, GroupLayout.PREFERRED_SIZE, 115, GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabelP, GroupLayout.PREFERRED_SIZE, 115, GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel12Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel12Layout.createParallelGroup(GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabelY, GroupLayout.PREFERRED_SIZE, 115, GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabelX, GroupLayout.PREFERRED_SIZE, 115, GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabelW, GroupLayout.PREFERRED_SIZE, 115, GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabelV, GroupLayout.PREFERRED_SIZE, 115, GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelU, GroupLayout.PREFERRED_SIZE, 115, GroupLayout.PREFERRED_SIZE))
                .addGap(143, 143, 143))
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGap(168, 168, 168)
                .addComponent(jLabel16, GroupLayout.PREFERRED_SIZE, 157, GroupLayout.PREFERRED_SIZE)
                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jLabel16, GroupLayout.PREFERRED_SIZE, 35, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel12Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel12Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel12Layout.createSequentialGroup()
                            .addGroup(jPanel12Layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabelF, GroupLayout.PREFERRED_SIZE, 60, GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabelK, GroupLayout.PREFERRED_SIZE, 60, GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabelG, GroupLayout.PREFERRED_SIZE, 60, GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabelH, GroupLayout.PREFERRED_SIZE, 60, GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabelI, GroupLayout.PREFERRED_SIZE, 60, GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jLabelJ, GroupLayout.PREFERRED_SIZE, 60, GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel12Layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelU, GroupLayout.PREFERRED_SIZE, 60, GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelP, GroupLayout.PREFERRED_SIZE, 60, GroupLayout.PREFERRED_SIZE))
                        .addGroup(GroupLayout.Alignment.TRAILING, jPanel12Layout.createSequentialGroup()
                            .addComponent(jLabelL, GroupLayout.PREFERRED_SIZE, 60, GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabelM, GroupLayout.PREFERRED_SIZE, 60, GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabelN, GroupLayout.PREFERRED_SIZE, 60, GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabelO, GroupLayout.PREFERRED_SIZE, 60, GroupLayout.PREFERRED_SIZE))
                        .addGroup(GroupLayout.Alignment.TRAILING, jPanel12Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelV, GroupLayout.PREFERRED_SIZE, 60, GroupLayout.PREFERRED_SIZE)
                            .addGroup(GroupLayout.Alignment.TRAILING, jPanel12Layout.createSequentialGroup()
                                .addComponent(jLabelW, GroupLayout.PREFERRED_SIZE, 60, GroupLayout.PREFERRED_SIZE)
                                .addGap(11, 11, 11)
                                .addComponent(jLabelX, GroupLayout.PREFERRED_SIZE, 60, GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabelY, GroupLayout.PREFERRED_SIZE, 60, GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel12Layout.createSequentialGroup()
                                .addComponent(jLabelQ, GroupLayout.PREFERRED_SIZE, 60, GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabelR, GroupLayout.PREFERRED_SIZE, 60, GroupLayout.PREFERRED_SIZE)
                                .addGap(11, 11, 11)
                                .addComponent(jLabelS, GroupLayout.PREFERRED_SIZE, 60, GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabelT, GroupLayout.PREFERRED_SIZE, 60, GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addComponent(jLabelA, GroupLayout.PREFERRED_SIZE, 60, GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelB, GroupLayout.PREFERRED_SIZE, 60, GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelC, GroupLayout.PREFERRED_SIZE, 60, GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelD, GroupLayout.PREFERRED_SIZE, 60, GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabelE, GroupLayout.PREFERRED_SIZE, 60, GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addGroup(jPanel12Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel19, GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4, GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );

        jPanel6.setBackground(new Color(51, 51, 51));

        jPanel10.setBackground(new Color(51, 51, 51));

        GroupLayout jPanel10Layout = new GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGap(0, 293, Short.MAX_VALUE)
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGap(0, 41, Short.MAX_VALUE)
        );

        jPanel13.setBackground(new Color(51, 51, 51));

        GroupLayout jPanel13Layout = new GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGap(0, 293, Short.MAX_VALUE)
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGap(0, 41, Short.MAX_VALUE)
        );

        jPanel14.setBackground(new Color(51, 51, 51));

        GroupLayout jPanel14Layout = new GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGap(0, 52, Short.MAX_VALUE)
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGap(0, 41, Short.MAX_VALUE)
        );

        jLabel11.setFont(new Font("Tahoma", 0, 12)); // NOI18N
        jLabel11.setForeground(new Color(255, 255, 255));
        jLabel11.setIcon(new ImageIcon(getClass().getResource("/icons/floor.png"))); // NOI18N
        jLabel11.setText("VIEW OF HALL " + hall);
        jLabel11.setHorizontalTextPosition(SwingConstants.RIGHT);
        jLabel11.setIconTextGap(20);

        GroupLayout jPanel6Layout = new GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addComponent(jPanel10, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel13, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel11, GroupLayout.PREFERRED_SIZE, 154, GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57)
                .addComponent(jPanel14, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSeparator1, GroupLayout.PREFERRED_SIZE, 208, GroupLayout.PREFERRED_SIZE)
                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSeparator1, GroupLayout.PREFERRED_SIZE, 5, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel14, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11, GroupLayout.PREFERRED_SIZE, 41, GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, 321, Short.MAX_VALUE)
                .addComponent(jPanel10, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel13, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addGap(69, 69, 69))
        );

        GroupLayout jPanel1Layout = new GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel3, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel12, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel6, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jPanel2, GroupLayout.PREFERRED_SIZE, 1150, GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(619, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jPanel2, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel12, 546, 546, GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel6, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel3, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)))
        );

        GroupLayout layout = new GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGap(0, 2050, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGap(0, 680, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void LogoutClicked(java.awt.event.MouseEvent evt) {
        RunAndLogIn newwindow = new RunAndLogIn();
        newwindow.setVisible(true);
        this.setVisible(false);
        PopUp frm = new PopUp("You've been logged out correctly.");
        frm.setLocationRelativeTo(null);
        frm.setVisible(true);
    }                                    

    private void ViewClicked(java.awt.event.MouseEvent evt) {
        ViewRestaurant newwindow = new ViewRestaurant(UserLogin);
        newwindow.setVisible(true);
        this.setVisible(false);
    }                                    

    private void OrdersClicked(java.awt.event.MouseEvent evt) {
        AfterLogin newwindow = new AfterLogin(UserLogin);
        newwindow.setVisible(true);
        this.setVisible(false);
    }                                    

    private void MergeClicked(java.awt.event.MouseEvent evt) {
        MergeOrSplit newwindow = new MergeOrSplit(UserLogin,"merge");
        newwindow.setVisible(true);
        this.setVisible(false);
    }                                    

    private void SplitClicked(java.awt.event.MouseEvent evt) {
        MergeOrSplit newwindow = new MergeOrSplit(UserLogin,"split");
        newwindow.setVisible(true);
        this.setVisible(false);
    }                                    

    private void BookClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        Book newwindow = new Book(UserLogin);
        newwindow.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jLabel7MouseClicked

    private void TableClicked(java.awt.event.MouseEvent evt, String tableNumber) {//GEN-FIRST:event_jLabel47MouseClicked
        Order newwindow = new Order(UserLogin,"0", hall, tableNumber);
        newwindow.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jLabel47MouseClicked

    private void fillInComponents()
    {
        Connection conn = null;
        Statement stmt = null;
        ResultSet rs = null;
        int i=0;
        try {
            conn = ConnectionConfiguration.getConnection();
            stmt = conn.createStatement();
            String sql = "SELECT IDtable, Status FROM tables WHERE IDroom=" + hall;
            rs = stmt.executeQuery(sql);
            while(rs.next()){
                int id  = rs.getInt("IDtable");
                String status = rs.getString("Status");
                labelList.get(i).setText(""+id);
                if(status.contains("free")) {
                    labelList.get(i).setIcon(new ImageIcon(getClass().getResource("/icons/table_green.png"))); // NOI18N
                }
                if(status.contains("reserved")) {
                    labelList.get(i).setIcon(new ImageIcon(getClass().getResource("/icons/table_blue.png"))); // NOI18N
                }
                if(status.contains("taken")) {
                    labelList.get(i).setIcon(new ImageIcon(getClass().getResource("/icons/table_red.png"))); // NOI18N
                }
                i++;
            }
            rs.close();
        }
        catch(SQLException se)  { se.printStackTrace();}
        catch (Exception e) { e.printStackTrace(); }
        finally {
            try{ if(stmt!=null) conn.close(); }
            catch(SQLException se){ }
            try{ if(conn!=null) conn.close(); }
            catch(SQLException se){ se.printStackTrace(); }
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private JLabel jLabelVIEW;
    private JLabel jLabelT;
    private JLabel jLabel11;
    private JLabel jLabelD;
    private JLabel jLabelY;
    private JLabel jLabelA;
    private JLabel jLabelS;
    private JLabel jLabel16;
    private JLabel jLabelX;
    private JLabel jLabel19;
    private JLabel jLabelLOGOUT;
    private JLabel jLabelK;
    private JLabel jLabel3;
    private JLabel jLabelC;
    private JLabel jLabelF;
    private JLabel jLabelI;
    private JLabel jLabel4;
    private JLabel jLabelJ;
    private JLabel jLabelH;
    private JLabel jLabelG;
    private JLabel jLabelE;
    private JLabel jLabelL;
    private JLabel jLabelM;
    private JLabel jLabelN;
    private JLabel jLabelO;
    private JLabel jLabelP;
    private JLabel jLabelU;
    private JLabel jLabelORDERS;
    private JLabel jLabelR;
    private JLabel jLabelQ;
    private JLabel jLabelW;
    private JLabel jLabelV;
    private JLabel jLabelMERGE;
    private JLabel jLabelSPLIT;
    private JLabel jLabelBOOK;
    private JLabel jLabelB;
    private JPanel jPanel1;
    private JPanel jPanel10;
    private JPanel jPanel11;
    private JPanel jPanel12;
    private JPanel jPanel13;
    private JPanel jPanel14;
    private JPanel jPanel2;
    private JPanel jPanel3;
    private JPanel jPanel4;
    private JPanel jPanel5;
    private JPanel jPanel6;
    private JPanel jPanel7;
    private JPanel jPanel8;
    private JPanel jPanel9;
    private JSeparator jSeparator1;
    private JSeparator jSeparator2;
    private JSeparator jSeparator3;
    // End of variables declaration//GEN-END:variables
    private String table, order, option;
    private int hall, UserLogin;
    List<JLabel> labelList = new ArrayList<JLabel>();
}
